spring:
  profiles:
    active: dev
camel:
  springboot:
    shutdownTimeout: 1
    health.indicator.enabled: true
management.security.enabled: false

info.app.name: Spring boiler plate
info.app.description: This is a Spring boot boiler plate code.
info.app.version: 1.0.0

---

spring:
  profiles: mock
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: alertsdilip@gmail.com
    password:
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: alertsdilip@gmail.com
mailFrom: alertsdilip@gmail.com

message:   Hello from MOCK Profile
fromRoute: direct:input
toRoute: spring-ws:http://www.webservicex.net/country.asmx?webServiceTemplate=#webServiceTemplate&soapAction=http://www.webserviceX.NET/GetCountryByCountryCode
healthRoute: direct:health
dbNode: mock:output
selectNode: mock:output
---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: alertsdilip@gmail.com
    password:
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: alertsdilip@gmail.com
mailFrom: alertsdilip@gmail.com
message:   Hello from DEV Profile
fromRoute: timer:app?period=10s
toRoute: spring-ws:http://www.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?webServiceTemplate=#webServiceTemplate&soapAction=http://www.oorsprong.org/websamples.countryinfo/FullCountryInfo
healthRoute: timer:health?period=10s
dbNode: jdbc:dataSource
selectNode: sql:select * from countries where COUNTRY_CODE = :#countryCode?dataSource=#dataSource

---

spring:
  profiles: stage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz@gmail.com
    password:
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: xyz@gmail.com
mailFrom: xyz@gmail.com
message:    Hello from STAGE Profile

fromRoute: timer:health?period=10s
toRoute:  log:?level=INFO&showBody=true
healthRoute: timer:health?period=10s
dbNode: jdbc:dataSource
selectNode: sql:select * from countries where COUNTRY_CODE = :#countryCode?dataSource=#dataSource

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/localDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: xyz@gmail.com
    password:
    properties.mail.smtp.auth:  true
    properties.mail.smtp.starttls.enable: true

mailto: xyz@gmail.com
mailFrom: xyz@gmail.com

message:    Hello from PROD Profile

fromRoute: timer:health?period=10s
toRoute:  log:?level=INFO&showBody=true
healthRoute: timer:health?period=10s
dbNode: jdbc:dataSource
selectNode: sql:select * from countries where COUNTRY_CODE = :#countryCode?dataSource=#dataSource

---